<?php

namespace App\Controller\Admin;

use App\Entity\Gallery;
use App\Entity\Message;
use App\Entity\Service;
use App\Entity\Testimonial;
use App\Entity\User;
use App\Entity\Vehicle;
use App\Entity\VehicleType;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Config\UserMenu;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Translation\Translator;

class DashboardController extends AbstractDashboardController
{
    public function __construct(private readonly AdminUrlGenerator $urlGenerator)
    {
    }

    #[Route('/admin', name: 'admin')]
    public function index(): Response
    {
        $url = $this->urlGenerator->setController(UserCrudController::class)->generateUrl();
        return $this->redirect($url);
    }

    public function configureCrud(): Crud
    {
        return parent::configureCrud()
            ->setTimezone('Africa/Douala'); // TODO: Change the autogenerated stub
    }

    public function configureDashboard(): Dashboard
    {
        return Dashboard::new()
            ->setTitle('<img src="assets/images/marque/garage-v-parrot-logo-marque.png" alt="Logo de garage V. Parrot" class="img-fluid">')
            ->setFaviconPath('favicon-32x32.png')
            ->renderSidebarMinimized(false);
    }

    public function configureMenuItems(): iterable
    {
        yield MenuItem::linkToDashboard('Tableau de Bord', 'fa-solid fa-gauge');

        yield MenuItem::linkToCrud('Utilisateurs', 'fas fa-list', User::class);
        yield MenuItem::linkToCrud('Véhicules', 'fas fa-car', Vehicle::class);
        yield MenuItem::linkToCrud('Nos Services', 'fas fa-wrench', Service::class);
        yield MenuItem::linkToCrud('Témoignages', 'fas fa-handshake-alt', Testimonial::class);
        yield MenuItem::linkToCrud('Moteurs', 'fas fa-gas-pump', VehicleType::class);
        yield MenuItem::linkToCrud('Messages Reçus', 'fas fa-mail-bulk', Message::class);
        yield MenuItem::linkToCrud('Galerie de véhicule', 'fas fa-images', Gallery::class);
        yield MenuItem::linkToLogout('Déconnexion', 'fas fa-door-closed');
    }

    public function configureUserMenu(UserInterface $user): UserMenu
    {
        return parent::configureUserMenu($user)
            ->setName($user->getFullname())
            ->addMenuItems([
                MenuItem::linkToRoute('Mon Profil', 'fas fa-user-cog', 'profile', ['id' => $user->getId()]),
                MenuItem::linkToRoute('Accueil', 'fas fa-home', 'app_home'),
                MenuItem::linkToLogout('Déconnexion', 'fas fa-door-closed')
            ]);
    }
}
